modif test

diff --git a/CodePipeline/buildspec-test.yml b/CodePipeline/buildspec-test.yml
--- a/CodePipeline/buildspec-test.yml
+++ b/CodePipeline/buildspec-test.yml
@@ -3,26 +3,27 @@ version: 0.2
 phases:
   install:
     commands:
-      # Install AWS CLI (already available in CodeBuild environment, but just in case)
-      - echo "Installing AWS CLI if not already available..."
-      - if ! command -v aws &> /dev/null; then
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
-          unzip awscliv2.zip;
-          sudo ./aws/install;
-        fi
-      # Verify AWS CLI installation
+      - #echo "Installing AWS CLI if not already available..."
+      - |
+          if ! command -v aws &> /dev/null; then
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
+            unzip awscliv2.zip;
+            sudo ./aws/install;
+          fi
       - aws --version
 
   build:
     commands:
-      - echo "Running tests..."
-      # Set up kubeconfig for EKS, assuming a role if necessary
+      - #echo "Running tests..."
       - aws eks update-kubeconfig --region eu-west-3 --name webservice-cluster --alias webservice-cluster --role-arn arn:aws:iam::654654192380:role/EKSClusterRole-webservice-dev
-      # Find the load balancer DNS name associated with WordPress
-      - echo "Retrieving Load Balancer DNS for WordPress service..."
-      - export LOAD_BALANCER_URL=$(aws elb describe-load-balancers --query "LoadBalancerDescriptions[?contains(DNSName, 'wordpress')].DNSName" --output text)
-      # Check if the LOAD_BALANCER_URL is set and handle error
-      - test -n "$LOAD_BALANCER_URL" && echo "Load Balancer URL found: $LOAD_BALANCER_URL" || { echo "Load Balancer URL not found for WordPress."; exit 1; }
-      # Test access to the WordPress site
+      - #echo "Retrieving Load Balancer DNS for WordPress service..."
+      - |
+          LOAD_BALANCER_URL=$(aws elb describe-load-balancers --query "LoadBalancerDescriptions[?contains(DNSName, 'wordpress')].DNSName" --output text)
+          if [ -z "$LOAD_BALANCER_URL" ]; then
+            echo "Load Balancer URL not found for WordPress.";
+            exit 1;
+          else
+            echo "Load Balancer URL found: $LOAD_BALANCER_URL";
+          fi
       - echo "Testing access to WordPress..."
       - curl -I http://$LOAD_BALANCER_URL:8080
